name = "xiaodian2"
main = "_worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[site]
bucket = "."

[build]
command = ""
build_output_directory = "."
watch_dir = "."

[env.production]
routes = [
  { pattern = "*/*", zone_name = "*" }
]
